### PR TITLE
Don't mention /talk if it doesn't work, and show full announcements i…

### PR DESCRIPTION
**Pull request by manooh**
…nstead of excerpts on frontpage.

It is frustrating to see excerpts with half finished sentences that don't link to the full article, so the full text should be shown in announcements.
Also, frontpage and contact/about pages shouldn't mention /talk if that isn't working.

I haven't tested the changes.

### CODE REVIEW

**Comment by danielvalentin** [comment]
Looks great. We'll pull this ASAP. Thanks for the contribution!

**Comment by manooh** [comment]
sweet! :-)

**Comment by manooh** [comment]
hey... I broke something. morningpages.net/talk now throws an error instead of the intended 404, and the announcements on the frontpage are still only half rendered. At this point I can't mess around in the code blindly, either I need to set up a local dev environment or maybe you can have a look? :-)

**Comment by danielvalentin** [comment]
Aah, that's my bad. I didn't test the changes, just looked it over. It's an easy fix, I'll get it sorted at the latest this weekend. No sweat!

**Pull request merged**
